### ISSUE TITLE
Marshmallow

### ISSUE THREAD

**Issue by dausruddin** [MohammadAG/Xposed-Screenshot-Delay-Remover#1]
Would you mind to make it work on marshmallow?

**Comment by terrorist96** [comment]
Can confirm it doesn't work on MM. Relevant error from log:

> 12-21 20:57:31.286 I/Xposed  (  954): Failed to hook PhoneWindowManager, screenshot delays are here to stay: java.lang.ClassNotFoundException: com.android.internal.policy.impl.PhoneWindowManager

**Comment by linbo0518** [comment]
It doesn't work on marshmallow,please fix it,Thanks~~~

**Comment by terrorist96** [comment]
Sorry to say, but it doesn't look like it will be fixed. MohammadAG hasn't made any commits on Github since October 17, 2015. Four months and no commits.
Plus, this specific module has had only one commit, on April 25, 2015. That's over 9 months ago. Safe to say that this is no longer being supported.

**Comment by linbo0518** [comment]
https://github.com/bin456789/Xposed-Screenshot-Delay-Remover

it work fine on MM

**Comment by terrorist96** [comment]
Nice find!

**Comment by dausruddin** [comment]
Seems that @bin456789 uploaded his modded module into xposed repo. Nice move man!!!
Im gonna close this issue and assume @MohammadAG ScreenshotDelayRemover module is dead.

**Comment by bin456789** [comment]
Yes I have uploaded it into xposed repo.
I credited @MohammadAG in the module description.
So I think that should be OK.
